name: Run Python Script on Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "*/7 * * * *"  # Executes every 3 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      GMAIL_KEY: ${{ secrets.GMAIL_KEY }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Fetches the repository code into the workflow environment

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Python version to use
      
      - name: Upgrade pip
        run: pip install --upgrade pip # Upgrading pip

      - name: Install dependencies
        run: pip install -r requirements.txt  # Installs dependencies from requirements.txt

      - name: Run the script
        run: python main.py  # Runs the Python script
